chartConfig:
  config:
    label: Comments on issues & PRs
    selectedField: issues_total_comments
    showBigNumberLabel: true
  type: big_number
contentType: chart
dashboardSlug: github-repo-explorer
spaceSlug: github
metricQuery:
  dimensions: []
  exploreName: issues
  filters: {}
  limit: 1
  metrics:
    - issues_total_comments
  sorts: []
  tableCalculations: []
name: Comments
slug: comments-kpi
tableConfig:
  columnOrder:
    - issues_total_comments
tableName: issues
version: 1
