# put your configuration values here

# pages (of 100 records) pulled per GitHub resource per run
pages_per_resource = 5

[runtime]
log_level="WARNING"  # the system log level of dlt
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/reference/telemetry
dlthub_telemetry = true
workspace_id = "84e1c147-432a-45db-9962-789889fd664f"
organization_id = "1548a6a7-1722-4931-8d08-9a794561f2a2"

[workspace.settings]
name = "github-demo"
